---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-prod-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: flask-api
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30300
    protocol: TCP
