---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-dev-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: berktugsnbck/flask-app:latest
        ports:
          - containerPort: 5001
