---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-dev-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: flask-api
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30100
    protocol: TCP
